# Generated by Django 4.1.1 on 2022-09-17 05:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0003_alter_user_phone'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Courses',
            new_name='Course',
        ),
    ]
