# Generated by Django 4.1.1 on 2022-09-17 05:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0005_alter_course_duration'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='course',
            name='duration',
        ),
    ]
